'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AdminCatalogos
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''ddlCatalogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCatalogo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''gvDetalle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvDetalle As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''btAgregar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btAgregar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ddlTipoProducto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoProducto As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''gvDetalleDocumentos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvDetalleDocumentos As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''btGuardarDocumentos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btGuardarDocumentos As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''tbHabilitaCentinela control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbHabilitaCentinela As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbHabilitaT24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbHabilitaT24 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbProductoPF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbProductoPF As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbDiasAplazado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDiasAplazado As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbTipoNIT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTipoNIT As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbPaisDefecto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbPaisDefecto As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btGuardarParametros control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btGuardarParametros As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''tbCodigo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCodigo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbDescripcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDescripcion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cbHabilitado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbHabilitado As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''dvAdicional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvAdicional As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''cbAdicional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbAdicional As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lbCatalogoVinculados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCatalogoVinculados As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''gvDetalleVinculados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvDetalleVinculados As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''btGuardar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btGuardar As Global.System.Web.UI.WebControls.Button
End Class
