'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace Credito_Directo
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SchemaFile", [Namespace]:="http://www.ultimus.com/Credito_Directo_Empresarial"),  _
     System.SerializableAttribute()>  _
    Partial Public Class SchemaFile
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SchemaFileNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SchemaDataField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SchemaFileName() As String
            Get
                Return Me.SchemaFileNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SchemaFileNameField, value) <> true) Then
                    Me.SchemaFileNameField = value
                    Me.RaisePropertyChanged("SchemaFileName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property SchemaData() As String
            Get
                Return Me.SchemaDataField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SchemaDataField, value) <> true) Then
                    Me.SchemaDataField = value
                    Me.RaisePropertyChanged("SchemaData")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CTaskInfo", [Namespace]:="http://www.ultimus.com/Credito_Directo_Empresarial"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CTaskInfo
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private m_strStepLabelField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private m_strSummaryField As String
        
        Private m_nIncidentNumField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property m_strStepLabel() As String
            Get
                Return Me.m_strStepLabelField
            End Get
            Set
                If (Object.ReferenceEquals(Me.m_strStepLabelField, value) <> true) Then
                    Me.m_strStepLabelField = value
                    Me.RaisePropertyChanged("m_strStepLabel")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property m_strSummary() As String
            Get
                Return Me.m_strSummaryField
            End Get
            Set
                If (Object.ReferenceEquals(Me.m_strSummaryField, value) <> true) Then
                    Me.m_strSummaryField = value
                    Me.RaisePropertyChanged("m_strSummary")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=2)>  _
        Public Property m_nIncidentNum() As Integer
            Get
                Return Me.m_nIncidentNumField
            End Get
            Set
                If (Me.m_nIncidentNumField.Equals(value) <> true) Then
                    Me.m_nIncidentNumField = value
                    Me.RaisePropertyChanged("m_nIncidentNum")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.ultimus.com/Credito_Directo_Empresarial", ConfigurationName:="Credito_Directo.Credito_Directo_EmpresarialSoap")>  _
    Public Interface Credito_Directo_EmpresarialSoap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento strUserName del espacio de nombres http://www.ultimus.com/Credito_Directo_Empresarial no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ultimus.com/Credito_Directo_Empresarial/GetLaunchInformation", ReplyAction:="*")>  _
        Function GetLaunchInformation(ByVal request As Credito_Directo.GetLaunchInformationRequest) As Credito_Directo.GetLaunchInformationResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento strUserName del espacio de nombres http://www.ultimus.com/Credito_Directo_Empresarial no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ultimus.com/Credito_Directo_Empresarial/LaunchIncident", ReplyAction:="*")>  _
        Function LaunchIncident(ByVal request As Credito_Directo.LaunchIncidentRequest) As Credito_Directo.LaunchIncidentResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento strUserName del espacio de nombres http://www.ultimus.com/Credito_Directo_Empresarial no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ultimus.com/Credito_Directo_Empresarial/GetActiveTasks", ReplyAction:="*")>  _
        Function GetActiveTasks(ByVal request As Credito_Directo.GetActiveTasksRequest) As Credito_Directo.GetActiveTasksResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento strUserName del espacio de nombres http://www.ultimus.com/Credito_Directo_Empresarial no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ultimus.com/Credito_Directo_Empresarial/AbortIncident", ReplyAction:="*")>  _
        Function AbortIncident(ByVal request As Credito_Directo.AbortIncidentRequest) As Credito_Directo.AbortIncidentResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento strUserName del espacio de nombres http://www.ultimus.com/Credito_Directo_Empresarial no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ultimus.com/Credito_Directo_Empresarial/GetTaskInformation", ReplyAction:="*")>  _
        Function GetTaskInformation(ByVal request As Credito_Directo.GetTaskInformationRequest) As Credito_Directo.GetTaskInformationResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento strUserName del espacio de nombres http://www.ultimus.com/Credito_Directo_Empresarial no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ultimus.com/Credito_Directo_Empresarial/CompleteStep", ReplyAction:="*")>  _
        Function CompleteStep(ByVal request As Credito_Directo.CompleteStepRequest) As Credito_Directo.CompleteStepResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento strUserName del espacio de nombres http://www.ultimus.com/Credito_Directo_Empresarial no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ultimus.com/Credito_Directo_Empresarial/ReturnStep", ReplyAction:="*")>  _
        Function ReturnStep(ByVal request As Credito_Directo.ReturnStepRequest) As Credito_Directo.ReturnStepResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetLaunchInformationRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetLaunchInformation", [Namespace]:="http://www.ultimus.com/Credito_Directo_Empresarial", Order:=0)>  _
        Public Body As Credito_Directo.GetLaunchInformationRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Credito_Directo.GetLaunchInformationRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/Credito_Directo_Empresarial")>  _
    Partial Public Class GetLaunchInformationRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strUserName As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strUserName As String)
            MyBase.New
            Me.strUserName = strUserName
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetLaunchInformationResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetLaunchInformationResponse", [Namespace]:="http://www.ultimus.com/Credito_Directo_Empresarial", Order:=0)>  _
        Public Body As Credito_Directo.GetLaunchInformationResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Credito_Directo.GetLaunchInformationResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/Credito_Directo_Empresarial")>  _
    Partial Public Class GetLaunchInformationResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public GetLaunchInformationResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public BeginSchema() As Credito_Directo.SchemaFile
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public strDefaultXML As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public strError As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetLaunchInformationResult As Boolean, ByVal BeginSchema() As Credito_Directo.SchemaFile, ByVal strDefaultXML As String, ByVal strError As String)
            MyBase.New
            Me.GetLaunchInformationResult = GetLaunchInformationResult
            Me.BeginSchema = BeginSchema
            Me.strDefaultXML = strDefaultXML
            Me.strError = strError
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LaunchIncidentRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LaunchIncident", [Namespace]:="http://www.ultimus.com/Credito_Directo_Empresarial", Order:=0)>  _
        Public Body As Credito_Directo.LaunchIncidentRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Credito_Directo.LaunchIncidentRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/Credito_Directo_Empresarial")>  _
    Partial Public Class LaunchIncidentRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strUserName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public strSummary As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public strMemo As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public bDisableAbort As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public nPriority As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public strXML As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=6)>  _
        Public bValidateXML As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strUserName As String, ByVal strSummary As String, ByVal strMemo As String, ByVal bDisableAbort As Boolean, ByVal nPriority As Integer, ByVal strXML As String, ByVal bValidateXML As Boolean)
            MyBase.New
            Me.strUserName = strUserName
            Me.strSummary = strSummary
            Me.strMemo = strMemo
            Me.bDisableAbort = bDisableAbort
            Me.nPriority = nPriority
            Me.strXML = strXML
            Me.bValidateXML = bValidateXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LaunchIncidentResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LaunchIncidentResponse", [Namespace]:="http://www.ultimus.com/Credito_Directo_Empresarial", Order:=0)>  _
        Public Body As Credito_Directo.LaunchIncidentResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Credito_Directo.LaunchIncidentResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/Credito_Directo_Empresarial")>  _
    Partial Public Class LaunchIncidentResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public LaunchIncidentResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public nIncidentNo As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public strError As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal LaunchIncidentResult As Boolean, ByVal nIncidentNo As Integer, ByVal strError As String)
            MyBase.New
            Me.LaunchIncidentResult = LaunchIncidentResult
            Me.nIncidentNo = nIncidentNo
            Me.strError = strError
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetActiveTasksRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetActiveTasks", [Namespace]:="http://www.ultimus.com/Credito_Directo_Empresarial", Order:=0)>  _
        Public Body As Credito_Directo.GetActiveTasksRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Credito_Directo.GetActiveTasksRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/Credito_Directo_Empresarial")>  _
    Partial Public Class GetActiveTasksRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strUserName As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strUserName As String)
            MyBase.New
            Me.strUserName = strUserName
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetActiveTasksResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetActiveTasksResponse", [Namespace]:="http://www.ultimus.com/Credito_Directo_Empresarial", Order:=0)>  _
        Public Body As Credito_Directo.GetActiveTasksResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Credito_Directo.GetActiveTasksResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/Credito_Directo_Empresarial")>  _
    Partial Public Class GetActiveTasksResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public GetActiveTasksResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public taskList() As Credito_Directo.CTaskInfo
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public strError As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetActiveTasksResult As Boolean, ByVal taskList() As Credito_Directo.CTaskInfo, ByVal strError As String)
            MyBase.New
            Me.GetActiveTasksResult = GetActiveTasksResult
            Me.taskList = taskList
            Me.strError = strError
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AbortIncidentRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="AbortIncident", [Namespace]:="http://www.ultimus.com/Credito_Directo_Empresarial", Order:=0)>  _
        Public Body As Credito_Directo.AbortIncidentRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Credito_Directo.AbortIncidentRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/Credito_Directo_Empresarial")>  _
    Partial Public Class AbortIncidentRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strUserName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public nIncidentNumber As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public strSummary As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strUserName As String, ByVal nIncidentNumber As Integer, ByVal strSummary As String)
            MyBase.New
            Me.strUserName = strUserName
            Me.nIncidentNumber = nIncidentNumber
            Me.strSummary = strSummary
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AbortIncidentResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="AbortIncidentResponse", [Namespace]:="http://www.ultimus.com/Credito_Directo_Empresarial", Order:=0)>  _
        Public Body As Credito_Directo.AbortIncidentResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Credito_Directo.AbortIncidentResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/Credito_Directo_Empresarial")>  _
    Partial Public Class AbortIncidentResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public AbortIncidentResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public strError As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AbortIncidentResult As Boolean, ByVal strError As String)
            MyBase.New
            Me.AbortIncidentResult = AbortIncidentResult
            Me.strError = strError
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetTaskInformationRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetTaskInformation", [Namespace]:="http://www.ultimus.com/Credito_Directo_Empresarial", Order:=0)>  _
        Public Body As Credito_Directo.GetTaskInformationRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Credito_Directo.GetTaskInformationRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/Credito_Directo_Empresarial")>  _
    Partial Public Class GetTaskInformationRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strUserName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public nIncidentNumber As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public strStepName As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strUserName As String, ByVal nIncidentNumber As Integer, ByVal strStepName As String)
            MyBase.New
            Me.strUserName = strUserName
            Me.nIncidentNumber = nIncidentNumber
            Me.strStepName = strStepName
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetTaskInformationResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetTaskInformationResponse", [Namespace]:="http://www.ultimus.com/Credito_Directo_Empresarial", Order:=0)>  _
        Public Body As Credito_Directo.GetTaskInformationResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Credito_Directo.GetTaskInformationResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/Credito_Directo_Empresarial")>  _
    Partial Public Class GetTaskInformationResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public GetTaskInformationResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public TaskSchema() As Credito_Directo.SchemaFile
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public strTaskXML As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public strError As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetTaskInformationResult As Boolean, ByVal TaskSchema() As Credito_Directo.SchemaFile, ByVal strTaskXML As String, ByVal strError As String)
            MyBase.New
            Me.GetTaskInformationResult = GetTaskInformationResult
            Me.TaskSchema = TaskSchema
            Me.strTaskXML = strTaskXML
            Me.strError = strError
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CompleteStepRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CompleteStep", [Namespace]:="http://www.ultimus.com/Credito_Directo_Empresarial", Order:=0)>  _
        Public Body As Credito_Directo.CompleteStepRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Credito_Directo.CompleteStepRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/Credito_Directo_Empresarial")>  _
    Partial Public Class CompleteStepRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strUserName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public nIncidentNumber As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public strStepName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public strSummary As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public strMemo As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=5)>  _
        Public bDisableAbort As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=6)>  _
        Public nPriority As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public strXML As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=8)>  _
        Public bValidateXML As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strUserName As String, ByVal nIncidentNumber As Integer, ByVal strStepName As String, ByVal strSummary As String, ByVal strMemo As String, ByVal bDisableAbort As Boolean, ByVal nPriority As Integer, ByVal strXML As String, ByVal bValidateXML As Boolean)
            MyBase.New
            Me.strUserName = strUserName
            Me.nIncidentNumber = nIncidentNumber
            Me.strStepName = strStepName
            Me.strSummary = strSummary
            Me.strMemo = strMemo
            Me.bDisableAbort = bDisableAbort
            Me.nPriority = nPriority
            Me.strXML = strXML
            Me.bValidateXML = bValidateXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CompleteStepResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CompleteStepResponse", [Namespace]:="http://www.ultimus.com/Credito_Directo_Empresarial", Order:=0)>  _
        Public Body As Credito_Directo.CompleteStepResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Credito_Directo.CompleteStepResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/Credito_Directo_Empresarial")>  _
    Partial Public Class CompleteStepResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public CompleteStepResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public nIncidentNumber As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public strError As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CompleteStepResult As Boolean, ByVal nIncidentNumber As Integer, ByVal strError As String)
            MyBase.New
            Me.CompleteStepResult = CompleteStepResult
            Me.nIncidentNumber = nIncidentNumber
            Me.strError = strError
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ReturnStepRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ReturnStep", [Namespace]:="http://www.ultimus.com/Credito_Directo_Empresarial", Order:=0)>  _
        Public Body As Credito_Directo.ReturnStepRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Credito_Directo.ReturnStepRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/Credito_Directo_Empresarial")>  _
    Partial Public Class ReturnStepRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strUserName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public nIncidentNumber As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public strStepName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public strSummary As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public strMemo As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=5)>  _
        Public bDisableAbort As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=6)>  _
        Public nPriority As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public strXML As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=8)>  _
        Public bValidateXML As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strUserName As String, ByVal nIncidentNumber As Integer, ByVal strStepName As String, ByVal strSummary As String, ByVal strMemo As String, ByVal bDisableAbort As Boolean, ByVal nPriority As Integer, ByVal strXML As String, ByVal bValidateXML As Boolean)
            MyBase.New
            Me.strUserName = strUserName
            Me.nIncidentNumber = nIncidentNumber
            Me.strStepName = strStepName
            Me.strSummary = strSummary
            Me.strMemo = strMemo
            Me.bDisableAbort = bDisableAbort
            Me.nPriority = nPriority
            Me.strXML = strXML
            Me.bValidateXML = bValidateXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ReturnStepResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ReturnStepResponse", [Namespace]:="http://www.ultimus.com/Credito_Directo_Empresarial", Order:=0)>  _
        Public Body As Credito_Directo.ReturnStepResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Credito_Directo.ReturnStepResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/Credito_Directo_Empresarial")>  _
    Partial Public Class ReturnStepResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public ReturnStepResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public nIncidentNumber As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public strError As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ReturnStepResult As Boolean, ByVal nIncidentNumber As Integer, ByVal strError As String)
            MyBase.New
            Me.ReturnStepResult = ReturnStepResult
            Me.nIncidentNumber = nIncidentNumber
            Me.strError = strError
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface Credito_Directo_EmpresarialSoapChannel
        Inherits Credito_Directo.Credito_Directo_EmpresarialSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Credito_Directo_EmpresarialSoapClient
        Inherits System.ServiceModel.ClientBase(Of Credito_Directo.Credito_Directo_EmpresarialSoap)
        Implements Credito_Directo.Credito_Directo_EmpresarialSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Credito_Directo_Credito_Directo_EmpresarialSoap_GetLaunchInformation(ByVal request As Credito_Directo.GetLaunchInformationRequest) As Credito_Directo.GetLaunchInformationResponse Implements Credito_Directo.Credito_Directo_EmpresarialSoap.GetLaunchInformation
            Return MyBase.Channel.GetLaunchInformation(request)
        End Function
        
        Public Function GetLaunchInformation(ByVal strUserName As String, <System.Runtime.InteropServices.OutAttribute()> ByRef BeginSchema() As Credito_Directo.SchemaFile, <System.Runtime.InteropServices.OutAttribute()> ByRef strDefaultXML As String, <System.Runtime.InteropServices.OutAttribute()> ByRef strError As String) As Boolean
            Dim inValue As Credito_Directo.GetLaunchInformationRequest = New Credito_Directo.GetLaunchInformationRequest()
            inValue.Body = New Credito_Directo.GetLaunchInformationRequestBody()
            inValue.Body.strUserName = strUserName
            Dim retVal As Credito_Directo.GetLaunchInformationResponse = CType(Me,Credito_Directo.Credito_Directo_EmpresarialSoap).GetLaunchInformation(inValue)
            BeginSchema = retVal.Body.BeginSchema
            strDefaultXML = retVal.Body.strDefaultXML
            strError = retVal.Body.strError
            Return retVal.Body.GetLaunchInformationResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Credito_Directo_Credito_Directo_EmpresarialSoap_LaunchIncident(ByVal request As Credito_Directo.LaunchIncidentRequest) As Credito_Directo.LaunchIncidentResponse Implements Credito_Directo.Credito_Directo_EmpresarialSoap.LaunchIncident
            Return MyBase.Channel.LaunchIncident(request)
        End Function
        
        Public Function LaunchIncident(ByVal strUserName As String, ByVal strSummary As String, ByVal strMemo As String, ByVal bDisableAbort As Boolean, ByVal nPriority As Integer, ByVal strXML As String, ByVal bValidateXML As Boolean, <System.Runtime.InteropServices.OutAttribute()> ByRef nIncidentNo As Integer, <System.Runtime.InteropServices.OutAttribute()> ByRef strError As String) As Boolean
            Dim inValue As Credito_Directo.LaunchIncidentRequest = New Credito_Directo.LaunchIncidentRequest()
            inValue.Body = New Credito_Directo.LaunchIncidentRequestBody()
            inValue.Body.strUserName = strUserName
            inValue.Body.strSummary = strSummary
            inValue.Body.strMemo = strMemo
            inValue.Body.bDisableAbort = bDisableAbort
            inValue.Body.nPriority = nPriority
            inValue.Body.strXML = strXML
            inValue.Body.bValidateXML = bValidateXML
            Dim retVal As Credito_Directo.LaunchIncidentResponse = CType(Me,Credito_Directo.Credito_Directo_EmpresarialSoap).LaunchIncident(inValue)
            nIncidentNo = retVal.Body.nIncidentNo
            strError = retVal.Body.strError
            Return retVal.Body.LaunchIncidentResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Credito_Directo_Credito_Directo_EmpresarialSoap_GetActiveTasks(ByVal request As Credito_Directo.GetActiveTasksRequest) As Credito_Directo.GetActiveTasksResponse Implements Credito_Directo.Credito_Directo_EmpresarialSoap.GetActiveTasks
            Return MyBase.Channel.GetActiveTasks(request)
        End Function
        
        Public Function GetActiveTasks(ByVal strUserName As String, <System.Runtime.InteropServices.OutAttribute()> ByRef taskList() As Credito_Directo.CTaskInfo, <System.Runtime.InteropServices.OutAttribute()> ByRef strError As String) As Boolean
            Dim inValue As Credito_Directo.GetActiveTasksRequest = New Credito_Directo.GetActiveTasksRequest()
            inValue.Body = New Credito_Directo.GetActiveTasksRequestBody()
            inValue.Body.strUserName = strUserName
            Dim retVal As Credito_Directo.GetActiveTasksResponse = CType(Me,Credito_Directo.Credito_Directo_EmpresarialSoap).GetActiveTasks(inValue)
            taskList = retVal.Body.taskList
            strError = retVal.Body.strError
            Return retVal.Body.GetActiveTasksResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Credito_Directo_Credito_Directo_EmpresarialSoap_AbortIncident(ByVal request As Credito_Directo.AbortIncidentRequest) As Credito_Directo.AbortIncidentResponse Implements Credito_Directo.Credito_Directo_EmpresarialSoap.AbortIncident
            Return MyBase.Channel.AbortIncident(request)
        End Function
        
        Public Function AbortIncident(ByVal strUserName As String, ByVal nIncidentNumber As Integer, ByVal strSummary As String, <System.Runtime.InteropServices.OutAttribute()> ByRef strError As String) As Boolean
            Dim inValue As Credito_Directo.AbortIncidentRequest = New Credito_Directo.AbortIncidentRequest()
            inValue.Body = New Credito_Directo.AbortIncidentRequestBody()
            inValue.Body.strUserName = strUserName
            inValue.Body.nIncidentNumber = nIncidentNumber
            inValue.Body.strSummary = strSummary
            Dim retVal As Credito_Directo.AbortIncidentResponse = CType(Me,Credito_Directo.Credito_Directo_EmpresarialSoap).AbortIncident(inValue)
            strError = retVal.Body.strError
            Return retVal.Body.AbortIncidentResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Credito_Directo_Credito_Directo_EmpresarialSoap_GetTaskInformation(ByVal request As Credito_Directo.GetTaskInformationRequest) As Credito_Directo.GetTaskInformationResponse Implements Credito_Directo.Credito_Directo_EmpresarialSoap.GetTaskInformation
            Return MyBase.Channel.GetTaskInformation(request)
        End Function
        
        Public Function GetTaskInformation(ByVal strUserName As String, ByVal nIncidentNumber As Integer, ByVal strStepName As String, <System.Runtime.InteropServices.OutAttribute()> ByRef TaskSchema() As Credito_Directo.SchemaFile, <System.Runtime.InteropServices.OutAttribute()> ByRef strTaskXML As String, <System.Runtime.InteropServices.OutAttribute()> ByRef strError As String) As Boolean
            Dim inValue As Credito_Directo.GetTaskInformationRequest = New Credito_Directo.GetTaskInformationRequest()
            inValue.Body = New Credito_Directo.GetTaskInformationRequestBody()
            inValue.Body.strUserName = strUserName
            inValue.Body.nIncidentNumber = nIncidentNumber
            inValue.Body.strStepName = strStepName
            Dim retVal As Credito_Directo.GetTaskInformationResponse = CType(Me,Credito_Directo.Credito_Directo_EmpresarialSoap).GetTaskInformation(inValue)
            TaskSchema = retVal.Body.TaskSchema
            strTaskXML = retVal.Body.strTaskXML
            strError = retVal.Body.strError
            Return retVal.Body.GetTaskInformationResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Credito_Directo_Credito_Directo_EmpresarialSoap_CompleteStep(ByVal request As Credito_Directo.CompleteStepRequest) As Credito_Directo.CompleteStepResponse Implements Credito_Directo.Credito_Directo_EmpresarialSoap.CompleteStep
            Return MyBase.Channel.CompleteStep(request)
        End Function
        
        Public Function CompleteStep(ByVal strUserName As String, ByRef nIncidentNumber As Integer, ByVal strStepName As String, ByVal strSummary As String, ByVal strMemo As String, ByVal bDisableAbort As Boolean, ByVal nPriority As Integer, ByVal strXML As String, ByVal bValidateXML As Boolean, <System.Runtime.InteropServices.OutAttribute()> ByRef strError As String) As Boolean
            Dim inValue As Credito_Directo.CompleteStepRequest = New Credito_Directo.CompleteStepRequest()
            inValue.Body = New Credito_Directo.CompleteStepRequestBody()
            inValue.Body.strUserName = strUserName
            inValue.Body.nIncidentNumber = nIncidentNumber
            inValue.Body.strStepName = strStepName
            inValue.Body.strSummary = strSummary
            inValue.Body.strMemo = strMemo
            inValue.Body.bDisableAbort = bDisableAbort
            inValue.Body.nPriority = nPriority
            inValue.Body.strXML = strXML
            inValue.Body.bValidateXML = bValidateXML
            Dim retVal As Credito_Directo.CompleteStepResponse = CType(Me,Credito_Directo.Credito_Directo_EmpresarialSoap).CompleteStep(inValue)
            nIncidentNumber = retVal.Body.nIncidentNumber
            strError = retVal.Body.strError
            Return retVal.Body.CompleteStepResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Credito_Directo_Credito_Directo_EmpresarialSoap_ReturnStep(ByVal request As Credito_Directo.ReturnStepRequest) As Credito_Directo.ReturnStepResponse Implements Credito_Directo.Credito_Directo_EmpresarialSoap.ReturnStep
            Return MyBase.Channel.ReturnStep(request)
        End Function
        
        Public Function ReturnStep(ByVal strUserName As String, ByRef nIncidentNumber As Integer, ByVal strStepName As String, ByVal strSummary As String, ByVal strMemo As String, ByVal bDisableAbort As Boolean, ByVal nPriority As Integer, ByVal strXML As String, ByVal bValidateXML As Boolean, <System.Runtime.InteropServices.OutAttribute()> ByRef strError As String) As Boolean
            Dim inValue As Credito_Directo.ReturnStepRequest = New Credito_Directo.ReturnStepRequest()
            inValue.Body = New Credito_Directo.ReturnStepRequestBody()
            inValue.Body.strUserName = strUserName
            inValue.Body.nIncidentNumber = nIncidentNumber
            inValue.Body.strStepName = strStepName
            inValue.Body.strSummary = strSummary
            inValue.Body.strMemo = strMemo
            inValue.Body.bDisableAbort = bDisableAbort
            inValue.Body.nPriority = nPriority
            inValue.Body.strXML = strXML
            inValue.Body.bValidateXML = bValidateXML
            Dim retVal As Credito_Directo.ReturnStepResponse = CType(Me,Credito_Directo.Credito_Directo_EmpresarialSoap).ReturnStep(inValue)
            nIncidentNumber = retVal.Body.nIncidentNumber
            strError = retVal.Body.strError
            Return retVal.Body.ReturnStepResult
        End Function
    End Class
End Namespace
