'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace Tramite_Asesorias
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SchemaFile", [Namespace]:="http://www.ultimus.com/AtencionTramiteAse"),  _
     System.SerializableAttribute()>  _
    Partial Public Class SchemaFile
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SchemaFileNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SchemaDataField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SchemaFileName() As String
            Get
                Return Me.SchemaFileNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SchemaFileNameField, value) <> true) Then
                    Me.SchemaFileNameField = value
                    Me.RaisePropertyChanged("SchemaFileName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property SchemaData() As String
            Get
                Return Me.SchemaDataField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SchemaDataField, value) <> true) Then
                    Me.SchemaDataField = value
                    Me.RaisePropertyChanged("SchemaData")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CTaskInfo", [Namespace]:="http://www.ultimus.com/AtencionTramiteAse"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CTaskInfo
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private m_strStepLabelField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private m_strSummaryField As String
        
        Private m_nIncidentNumField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property m_strStepLabel() As String
            Get
                Return Me.m_strStepLabelField
            End Get
            Set
                If (Object.ReferenceEquals(Me.m_strStepLabelField, value) <> true) Then
                    Me.m_strStepLabelField = value
                    Me.RaisePropertyChanged("m_strStepLabel")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property m_strSummary() As String
            Get
                Return Me.m_strSummaryField
            End Get
            Set
                If (Object.ReferenceEquals(Me.m_strSummaryField, value) <> true) Then
                    Me.m_strSummaryField = value
                    Me.RaisePropertyChanged("m_strSummary")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=2)>  _
        Public Property m_nIncidentNum() As Integer
            Get
                Return Me.m_nIncidentNumField
            End Get
            Set
                If (Me.m_nIncidentNumField.Equals(value) <> true) Then
                    Me.m_nIncidentNumField = value
                    Me.RaisePropertyChanged("m_nIncidentNum")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.ultimus.com/AtencionTramiteAse", ConfigurationName:="Tramite_Asesorias.AtencionTramiteAseSoap")>  _
    Public Interface AtencionTramiteAseSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ultimus.com/AtencionTramiteAse/GetLaunchInformation", ReplyAction:="*")>  _
        Function GetLaunchInformation(ByVal request As Tramite_Asesorias.GetLaunchInformationRequest) As Tramite_Asesorias.GetLaunchInformationResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ultimus.com/AtencionTramiteAse/GetLaunchInformation", ReplyAction:="*")>  _
        Function GetLaunchInformationAsync(ByVal request As Tramite_Asesorias.GetLaunchInformationRequest) As System.Threading.Tasks.Task(Of Tramite_Asesorias.GetLaunchInformationResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ultimus.com/AtencionTramiteAse/LaunchIncident", ReplyAction:="*")>  _
        Function LaunchIncident(ByVal request As Tramite_Asesorias.LaunchIncidentRequest) As Tramite_Asesorias.LaunchIncidentResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ultimus.com/AtencionTramiteAse/LaunchIncident", ReplyAction:="*")>  _
        Function LaunchIncidentAsync(ByVal request As Tramite_Asesorias.LaunchIncidentRequest) As System.Threading.Tasks.Task(Of Tramite_Asesorias.LaunchIncidentResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ultimus.com/AtencionTramiteAse/GetActiveTasks", ReplyAction:="*")>  _
        Function GetActiveTasks(ByVal request As Tramite_Asesorias.GetActiveTasksRequest) As Tramite_Asesorias.GetActiveTasksResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ultimus.com/AtencionTramiteAse/GetActiveTasks", ReplyAction:="*")>  _
        Function GetActiveTasksAsync(ByVal request As Tramite_Asesorias.GetActiveTasksRequest) As System.Threading.Tasks.Task(Of Tramite_Asesorias.GetActiveTasksResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ultimus.com/AtencionTramiteAse/AbortIncident", ReplyAction:="*")>  _
        Function AbortIncident(ByVal request As Tramite_Asesorias.AbortIncidentRequest) As Tramite_Asesorias.AbortIncidentResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ultimus.com/AtencionTramiteAse/AbortIncident", ReplyAction:="*")>  _
        Function AbortIncidentAsync(ByVal request As Tramite_Asesorias.AbortIncidentRequest) As System.Threading.Tasks.Task(Of Tramite_Asesorias.AbortIncidentResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ultimus.com/AtencionTramiteAse/GetTaskInformation", ReplyAction:="*")>  _
        Function GetTaskInformation(ByVal request As Tramite_Asesorias.GetTaskInformationRequest) As Tramite_Asesorias.GetTaskInformationResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ultimus.com/AtencionTramiteAse/GetTaskInformation", ReplyAction:="*")>  _
        Function GetTaskInformationAsync(ByVal request As Tramite_Asesorias.GetTaskInformationRequest) As System.Threading.Tasks.Task(Of Tramite_Asesorias.GetTaskInformationResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ultimus.com/AtencionTramiteAse/CompleteStep", ReplyAction:="*")>  _
        Function CompleteStep(ByVal request As Tramite_Asesorias.CompleteStepRequest) As Tramite_Asesorias.CompleteStepResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ultimus.com/AtencionTramiteAse/CompleteStep", ReplyAction:="*")>  _
        Function CompleteStepAsync(ByVal request As Tramite_Asesorias.CompleteStepRequest) As System.Threading.Tasks.Task(Of Tramite_Asesorias.CompleteStepResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ultimus.com/AtencionTramiteAse/ReturnStep", ReplyAction:="*")>  _
        Function ReturnStep(ByVal request As Tramite_Asesorias.ReturnStepRequest) As Tramite_Asesorias.ReturnStepResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ultimus.com/AtencionTramiteAse/ReturnStep", ReplyAction:="*")>  _
        Function ReturnStepAsync(ByVal request As Tramite_Asesorias.ReturnStepRequest) As System.Threading.Tasks.Task(Of Tramite_Asesorias.ReturnStepResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetLaunchInformationRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetLaunchInformation", [Namespace]:="http://www.ultimus.com/AtencionTramiteAse", Order:=0)>  _
        Public Body As Tramite_Asesorias.GetLaunchInformationRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Tramite_Asesorias.GetLaunchInformationRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/AtencionTramiteAse")>  _
    Partial Public Class GetLaunchInformationRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strUserName As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strUserName As String)
            MyBase.New
            Me.strUserName = strUserName
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetLaunchInformationResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetLaunchInformationResponse", [Namespace]:="http://www.ultimus.com/AtencionTramiteAse", Order:=0)>  _
        Public Body As Tramite_Asesorias.GetLaunchInformationResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Tramite_Asesorias.GetLaunchInformationResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/AtencionTramiteAse")>  _
    Partial Public Class GetLaunchInformationResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public GetLaunchInformationResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public BeginSchema() As Tramite_Asesorias.SchemaFile
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public strDefaultXML As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public strError As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetLaunchInformationResult As Boolean, ByVal BeginSchema() As Tramite_Asesorias.SchemaFile, ByVal strDefaultXML As String, ByVal strError As String)
            MyBase.New
            Me.GetLaunchInformationResult = GetLaunchInformationResult
            Me.BeginSchema = BeginSchema
            Me.strDefaultXML = strDefaultXML
            Me.strError = strError
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LaunchIncidentRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LaunchIncident", [Namespace]:="http://www.ultimus.com/AtencionTramiteAse", Order:=0)>  _
        Public Body As Tramite_Asesorias.LaunchIncidentRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Tramite_Asesorias.LaunchIncidentRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/AtencionTramiteAse")>  _
    Partial Public Class LaunchIncidentRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strUserName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public strSummary As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public strMemo As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public bDisableAbort As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public nPriority As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public strXML As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=6)>  _
        Public bValidateXML As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strUserName As String, ByVal strSummary As String, ByVal strMemo As String, ByVal bDisableAbort As Boolean, ByVal nPriority As Integer, ByVal strXML As String, ByVal bValidateXML As Boolean)
            MyBase.New
            Me.strUserName = strUserName
            Me.strSummary = strSummary
            Me.strMemo = strMemo
            Me.bDisableAbort = bDisableAbort
            Me.nPriority = nPriority
            Me.strXML = strXML
            Me.bValidateXML = bValidateXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LaunchIncidentResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LaunchIncidentResponse", [Namespace]:="http://www.ultimus.com/AtencionTramiteAse", Order:=0)>  _
        Public Body As Tramite_Asesorias.LaunchIncidentResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Tramite_Asesorias.LaunchIncidentResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/AtencionTramiteAse")>  _
    Partial Public Class LaunchIncidentResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public LaunchIncidentResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public nIncidentNo As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public strError As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal LaunchIncidentResult As Boolean, ByVal nIncidentNo As Integer, ByVal strError As String)
            MyBase.New
            Me.LaunchIncidentResult = LaunchIncidentResult
            Me.nIncidentNo = nIncidentNo
            Me.strError = strError
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetActiveTasksRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetActiveTasks", [Namespace]:="http://www.ultimus.com/AtencionTramiteAse", Order:=0)>  _
        Public Body As Tramite_Asesorias.GetActiveTasksRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Tramite_Asesorias.GetActiveTasksRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/AtencionTramiteAse")>  _
    Partial Public Class GetActiveTasksRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strUserName As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strUserName As String)
            MyBase.New
            Me.strUserName = strUserName
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetActiveTasksResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetActiveTasksResponse", [Namespace]:="http://www.ultimus.com/AtencionTramiteAse", Order:=0)>  _
        Public Body As Tramite_Asesorias.GetActiveTasksResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Tramite_Asesorias.GetActiveTasksResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/AtencionTramiteAse")>  _
    Partial Public Class GetActiveTasksResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public GetActiveTasksResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public taskList() As Tramite_Asesorias.CTaskInfo
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public strError As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetActiveTasksResult As Boolean, ByVal taskList() As Tramite_Asesorias.CTaskInfo, ByVal strError As String)
            MyBase.New
            Me.GetActiveTasksResult = GetActiveTasksResult
            Me.taskList = taskList
            Me.strError = strError
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AbortIncidentRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="AbortIncident", [Namespace]:="http://www.ultimus.com/AtencionTramiteAse", Order:=0)>  _
        Public Body As Tramite_Asesorias.AbortIncidentRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Tramite_Asesorias.AbortIncidentRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/AtencionTramiteAse")>  _
    Partial Public Class AbortIncidentRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strUserName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public nIncidentNumber As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public strSummary As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strUserName As String, ByVal nIncidentNumber As Integer, ByVal strSummary As String)
            MyBase.New
            Me.strUserName = strUserName
            Me.nIncidentNumber = nIncidentNumber
            Me.strSummary = strSummary
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AbortIncidentResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="AbortIncidentResponse", [Namespace]:="http://www.ultimus.com/AtencionTramiteAse", Order:=0)>  _
        Public Body As Tramite_Asesorias.AbortIncidentResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Tramite_Asesorias.AbortIncidentResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/AtencionTramiteAse")>  _
    Partial Public Class AbortIncidentResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public AbortIncidentResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public strError As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AbortIncidentResult As Boolean, ByVal strError As String)
            MyBase.New
            Me.AbortIncidentResult = AbortIncidentResult
            Me.strError = strError
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetTaskInformationRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetTaskInformation", [Namespace]:="http://www.ultimus.com/AtencionTramiteAse", Order:=0)>  _
        Public Body As Tramite_Asesorias.GetTaskInformationRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Tramite_Asesorias.GetTaskInformationRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/AtencionTramiteAse")>  _
    Partial Public Class GetTaskInformationRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strUserName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public nIncidentNumber As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public strStepName As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strUserName As String, ByVal nIncidentNumber As Integer, ByVal strStepName As String)
            MyBase.New
            Me.strUserName = strUserName
            Me.nIncidentNumber = nIncidentNumber
            Me.strStepName = strStepName
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetTaskInformationResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetTaskInformationResponse", [Namespace]:="http://www.ultimus.com/AtencionTramiteAse", Order:=0)>  _
        Public Body As Tramite_Asesorias.GetTaskInformationResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Tramite_Asesorias.GetTaskInformationResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/AtencionTramiteAse")>  _
    Partial Public Class GetTaskInformationResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public GetTaskInformationResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public TaskSchema() As Tramite_Asesorias.SchemaFile
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public strTaskXML As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public strError As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetTaskInformationResult As Boolean, ByVal TaskSchema() As Tramite_Asesorias.SchemaFile, ByVal strTaskXML As String, ByVal strError As String)
            MyBase.New
            Me.GetTaskInformationResult = GetTaskInformationResult
            Me.TaskSchema = TaskSchema
            Me.strTaskXML = strTaskXML
            Me.strError = strError
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CompleteStepRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CompleteStep", [Namespace]:="http://www.ultimus.com/AtencionTramiteAse", Order:=0)>  _
        Public Body As Tramite_Asesorias.CompleteStepRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Tramite_Asesorias.CompleteStepRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/AtencionTramiteAse")>  _
    Partial Public Class CompleteStepRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strUserName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public nIncidentNumber As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public strStepName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public strSummary As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public strMemo As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=5)>  _
        Public bDisableAbort As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=6)>  _
        Public nPriority As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public strXML As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=8)>  _
        Public bValidateXML As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strUserName As String, ByVal nIncidentNumber As Integer, ByVal strStepName As String, ByVal strSummary As String, ByVal strMemo As String, ByVal bDisableAbort As Boolean, ByVal nPriority As Integer, ByVal strXML As String, ByVal bValidateXML As Boolean)
            MyBase.New
            Me.strUserName = strUserName
            Me.nIncidentNumber = nIncidentNumber
            Me.strStepName = strStepName
            Me.strSummary = strSummary
            Me.strMemo = strMemo
            Me.bDisableAbort = bDisableAbort
            Me.nPriority = nPriority
            Me.strXML = strXML
            Me.bValidateXML = bValidateXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CompleteStepResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CompleteStepResponse", [Namespace]:="http://www.ultimus.com/AtencionTramiteAse", Order:=0)>  _
        Public Body As Tramite_Asesorias.CompleteStepResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Tramite_Asesorias.CompleteStepResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/AtencionTramiteAse")>  _
    Partial Public Class CompleteStepResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public CompleteStepResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public nIncidentNumber As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public strError As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CompleteStepResult As Boolean, ByVal nIncidentNumber As Integer, ByVal strError As String)
            MyBase.New
            Me.CompleteStepResult = CompleteStepResult
            Me.nIncidentNumber = nIncidentNumber
            Me.strError = strError
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ReturnStepRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ReturnStep", [Namespace]:="http://www.ultimus.com/AtencionTramiteAse", Order:=0)>  _
        Public Body As Tramite_Asesorias.ReturnStepRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Tramite_Asesorias.ReturnStepRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/AtencionTramiteAse")>  _
    Partial Public Class ReturnStepRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strUserName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public nIncidentNumber As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public strStepName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public strSummary As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public strMemo As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=5)>  _
        Public bDisableAbort As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=6)>  _
        Public nPriority As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public strXML As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=8)>  _
        Public bValidateXML As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strUserName As String, ByVal nIncidentNumber As Integer, ByVal strStepName As String, ByVal strSummary As String, ByVal strMemo As String, ByVal bDisableAbort As Boolean, ByVal nPriority As Integer, ByVal strXML As String, ByVal bValidateXML As Boolean)
            MyBase.New
            Me.strUserName = strUserName
            Me.nIncidentNumber = nIncidentNumber
            Me.strStepName = strStepName
            Me.strSummary = strSummary
            Me.strMemo = strMemo
            Me.bDisableAbort = bDisableAbort
            Me.nPriority = nPriority
            Me.strXML = strXML
            Me.bValidateXML = bValidateXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ReturnStepResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ReturnStepResponse", [Namespace]:="http://www.ultimus.com/AtencionTramiteAse", Order:=0)>  _
        Public Body As Tramite_Asesorias.ReturnStepResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Tramite_Asesorias.ReturnStepResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/AtencionTramiteAse")>  _
    Partial Public Class ReturnStepResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public ReturnStepResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public nIncidentNumber As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public strError As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ReturnStepResult As Boolean, ByVal nIncidentNumber As Integer, ByVal strError As String)
            MyBase.New
            Me.ReturnStepResult = ReturnStepResult
            Me.nIncidentNumber = nIncidentNumber
            Me.strError = strError
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface AtencionTramiteAseSoapChannel
        Inherits Tramite_Asesorias.AtencionTramiteAseSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class AtencionTramiteAseSoapClient
        Inherits System.ServiceModel.ClientBase(Of Tramite_Asesorias.AtencionTramiteAseSoap)
        Implements Tramite_Asesorias.AtencionTramiteAseSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Tramite_Asesorias_AtencionTramiteAseSoap_GetLaunchInformation(ByVal request As Tramite_Asesorias.GetLaunchInformationRequest) As Tramite_Asesorias.GetLaunchInformationResponse Implements Tramite_Asesorias.AtencionTramiteAseSoap.GetLaunchInformation
            Return MyBase.Channel.GetLaunchInformation(request)
        End Function
        
        Public Function GetLaunchInformation(ByVal strUserName As String, <System.Runtime.InteropServices.OutAttribute()> ByRef BeginSchema() As Tramite_Asesorias.SchemaFile, <System.Runtime.InteropServices.OutAttribute()> ByRef strDefaultXML As String, <System.Runtime.InteropServices.OutAttribute()> ByRef strError As String) As Boolean
            Dim inValue As Tramite_Asesorias.GetLaunchInformationRequest = New Tramite_Asesorias.GetLaunchInformationRequest()
            inValue.Body = New Tramite_Asesorias.GetLaunchInformationRequestBody()
            inValue.Body.strUserName = strUserName
            Dim retVal As Tramite_Asesorias.GetLaunchInformationResponse = CType(Me,Tramite_Asesorias.AtencionTramiteAseSoap).GetLaunchInformation(inValue)
            BeginSchema = retVal.Body.BeginSchema
            strDefaultXML = retVal.Body.strDefaultXML
            strError = retVal.Body.strError
            Return retVal.Body.GetLaunchInformationResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Tramite_Asesorias_AtencionTramiteAseSoap_GetLaunchInformationAsync(ByVal request As Tramite_Asesorias.GetLaunchInformationRequest) As System.Threading.Tasks.Task(Of Tramite_Asesorias.GetLaunchInformationResponse) Implements Tramite_Asesorias.AtencionTramiteAseSoap.GetLaunchInformationAsync
            Return MyBase.Channel.GetLaunchInformationAsync(request)
        End Function
        
        Public Function GetLaunchInformationAsync(ByVal strUserName As String) As System.Threading.Tasks.Task(Of Tramite_Asesorias.GetLaunchInformationResponse)
            Dim inValue As Tramite_Asesorias.GetLaunchInformationRequest = New Tramite_Asesorias.GetLaunchInformationRequest()
            inValue.Body = New Tramite_Asesorias.GetLaunchInformationRequestBody()
            inValue.Body.strUserName = strUserName
            Return CType(Me,Tramite_Asesorias.AtencionTramiteAseSoap).GetLaunchInformationAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Tramite_Asesorias_AtencionTramiteAseSoap_LaunchIncident(ByVal request As Tramite_Asesorias.LaunchIncidentRequest) As Tramite_Asesorias.LaunchIncidentResponse Implements Tramite_Asesorias.AtencionTramiteAseSoap.LaunchIncident
            Return MyBase.Channel.LaunchIncident(request)
        End Function
        
        Public Function LaunchIncident(ByVal strUserName As String, ByVal strSummary As String, ByVal strMemo As String, ByVal bDisableAbort As Boolean, ByVal nPriority As Integer, ByVal strXML As String, ByVal bValidateXML As Boolean, <System.Runtime.InteropServices.OutAttribute()> ByRef nIncidentNo As Integer, <System.Runtime.InteropServices.OutAttribute()> ByRef strError As String) As Boolean
            Dim inValue As Tramite_Asesorias.LaunchIncidentRequest = New Tramite_Asesorias.LaunchIncidentRequest()
            inValue.Body = New Tramite_Asesorias.LaunchIncidentRequestBody()
            inValue.Body.strUserName = strUserName
            inValue.Body.strSummary = strSummary
            inValue.Body.strMemo = strMemo
            inValue.Body.bDisableAbort = bDisableAbort
            inValue.Body.nPriority = nPriority
            inValue.Body.strXML = strXML
            inValue.Body.bValidateXML = bValidateXML
            Dim retVal As Tramite_Asesorias.LaunchIncidentResponse = CType(Me,Tramite_Asesorias.AtencionTramiteAseSoap).LaunchIncident(inValue)
            nIncidentNo = retVal.Body.nIncidentNo
            strError = retVal.Body.strError
            Return retVal.Body.LaunchIncidentResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Tramite_Asesorias_AtencionTramiteAseSoap_LaunchIncidentAsync(ByVal request As Tramite_Asesorias.LaunchIncidentRequest) As System.Threading.Tasks.Task(Of Tramite_Asesorias.LaunchIncidentResponse) Implements Tramite_Asesorias.AtencionTramiteAseSoap.LaunchIncidentAsync
            Return MyBase.Channel.LaunchIncidentAsync(request)
        End Function
        
        Public Function LaunchIncidentAsync(ByVal strUserName As String, ByVal strSummary As String, ByVal strMemo As String, ByVal bDisableAbort As Boolean, ByVal nPriority As Integer, ByVal strXML As String, ByVal bValidateXML As Boolean) As System.Threading.Tasks.Task(Of Tramite_Asesorias.LaunchIncidentResponse)
            Dim inValue As Tramite_Asesorias.LaunchIncidentRequest = New Tramite_Asesorias.LaunchIncidentRequest()
            inValue.Body = New Tramite_Asesorias.LaunchIncidentRequestBody()
            inValue.Body.strUserName = strUserName
            inValue.Body.strSummary = strSummary
            inValue.Body.strMemo = strMemo
            inValue.Body.bDisableAbort = bDisableAbort
            inValue.Body.nPriority = nPriority
            inValue.Body.strXML = strXML
            inValue.Body.bValidateXML = bValidateXML
            Return CType(Me,Tramite_Asesorias.AtencionTramiteAseSoap).LaunchIncidentAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Tramite_Asesorias_AtencionTramiteAseSoap_GetActiveTasks(ByVal request As Tramite_Asesorias.GetActiveTasksRequest) As Tramite_Asesorias.GetActiveTasksResponse Implements Tramite_Asesorias.AtencionTramiteAseSoap.GetActiveTasks
            Return MyBase.Channel.GetActiveTasks(request)
        End Function
        
        Public Function GetActiveTasks(ByVal strUserName As String, <System.Runtime.InteropServices.OutAttribute()> ByRef taskList() As Tramite_Asesorias.CTaskInfo, <System.Runtime.InteropServices.OutAttribute()> ByRef strError As String) As Boolean
            Dim inValue As Tramite_Asesorias.GetActiveTasksRequest = New Tramite_Asesorias.GetActiveTasksRequest()
            inValue.Body = New Tramite_Asesorias.GetActiveTasksRequestBody()
            inValue.Body.strUserName = strUserName
            Dim retVal As Tramite_Asesorias.GetActiveTasksResponse = CType(Me,Tramite_Asesorias.AtencionTramiteAseSoap).GetActiveTasks(inValue)
            taskList = retVal.Body.taskList
            strError = retVal.Body.strError
            Return retVal.Body.GetActiveTasksResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Tramite_Asesorias_AtencionTramiteAseSoap_GetActiveTasksAsync(ByVal request As Tramite_Asesorias.GetActiveTasksRequest) As System.Threading.Tasks.Task(Of Tramite_Asesorias.GetActiveTasksResponse) Implements Tramite_Asesorias.AtencionTramiteAseSoap.GetActiveTasksAsync
            Return MyBase.Channel.GetActiveTasksAsync(request)
        End Function
        
        Public Function GetActiveTasksAsync(ByVal strUserName As String) As System.Threading.Tasks.Task(Of Tramite_Asesorias.GetActiveTasksResponse)
            Dim inValue As Tramite_Asesorias.GetActiveTasksRequest = New Tramite_Asesorias.GetActiveTasksRequest()
            inValue.Body = New Tramite_Asesorias.GetActiveTasksRequestBody()
            inValue.Body.strUserName = strUserName
            Return CType(Me,Tramite_Asesorias.AtencionTramiteAseSoap).GetActiveTasksAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Tramite_Asesorias_AtencionTramiteAseSoap_AbortIncident(ByVal request As Tramite_Asesorias.AbortIncidentRequest) As Tramite_Asesorias.AbortIncidentResponse Implements Tramite_Asesorias.AtencionTramiteAseSoap.AbortIncident
            Return MyBase.Channel.AbortIncident(request)
        End Function
        
        Public Function AbortIncident(ByVal strUserName As String, ByVal nIncidentNumber As Integer, ByVal strSummary As String, <System.Runtime.InteropServices.OutAttribute()> ByRef strError As String) As Boolean
            Dim inValue As Tramite_Asesorias.AbortIncidentRequest = New Tramite_Asesorias.AbortIncidentRequest()
            inValue.Body = New Tramite_Asesorias.AbortIncidentRequestBody()
            inValue.Body.strUserName = strUserName
            inValue.Body.nIncidentNumber = nIncidentNumber
            inValue.Body.strSummary = strSummary
            Dim retVal As Tramite_Asesorias.AbortIncidentResponse = CType(Me,Tramite_Asesorias.AtencionTramiteAseSoap).AbortIncident(inValue)
            strError = retVal.Body.strError
            Return retVal.Body.AbortIncidentResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Tramite_Asesorias_AtencionTramiteAseSoap_AbortIncidentAsync(ByVal request As Tramite_Asesorias.AbortIncidentRequest) As System.Threading.Tasks.Task(Of Tramite_Asesorias.AbortIncidentResponse) Implements Tramite_Asesorias.AtencionTramiteAseSoap.AbortIncidentAsync
            Return MyBase.Channel.AbortIncidentAsync(request)
        End Function
        
        Public Function AbortIncidentAsync(ByVal strUserName As String, ByVal nIncidentNumber As Integer, ByVal strSummary As String) As System.Threading.Tasks.Task(Of Tramite_Asesorias.AbortIncidentResponse)
            Dim inValue As Tramite_Asesorias.AbortIncidentRequest = New Tramite_Asesorias.AbortIncidentRequest()
            inValue.Body = New Tramite_Asesorias.AbortIncidentRequestBody()
            inValue.Body.strUserName = strUserName
            inValue.Body.nIncidentNumber = nIncidentNumber
            inValue.Body.strSummary = strSummary
            Return CType(Me,Tramite_Asesorias.AtencionTramiteAseSoap).AbortIncidentAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Tramite_Asesorias_AtencionTramiteAseSoap_GetTaskInformation(ByVal request As Tramite_Asesorias.GetTaskInformationRequest) As Tramite_Asesorias.GetTaskInformationResponse Implements Tramite_Asesorias.AtencionTramiteAseSoap.GetTaskInformation
            Return MyBase.Channel.GetTaskInformation(request)
        End Function
        
        Public Function GetTaskInformation(ByVal strUserName As String, ByVal nIncidentNumber As Integer, ByVal strStepName As String, <System.Runtime.InteropServices.OutAttribute()> ByRef TaskSchema() As Tramite_Asesorias.SchemaFile, <System.Runtime.InteropServices.OutAttribute()> ByRef strTaskXML As String, <System.Runtime.InteropServices.OutAttribute()> ByRef strError As String) As Boolean
            Dim inValue As Tramite_Asesorias.GetTaskInformationRequest = New Tramite_Asesorias.GetTaskInformationRequest()
            inValue.Body = New Tramite_Asesorias.GetTaskInformationRequestBody()
            inValue.Body.strUserName = strUserName
            inValue.Body.nIncidentNumber = nIncidentNumber
            inValue.Body.strStepName = strStepName
            Dim retVal As Tramite_Asesorias.GetTaskInformationResponse = CType(Me,Tramite_Asesorias.AtencionTramiteAseSoap).GetTaskInformation(inValue)
            TaskSchema = retVal.Body.TaskSchema
            strTaskXML = retVal.Body.strTaskXML
            strError = retVal.Body.strError
            Return retVal.Body.GetTaskInformationResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Tramite_Asesorias_AtencionTramiteAseSoap_GetTaskInformationAsync(ByVal request As Tramite_Asesorias.GetTaskInformationRequest) As System.Threading.Tasks.Task(Of Tramite_Asesorias.GetTaskInformationResponse) Implements Tramite_Asesorias.AtencionTramiteAseSoap.GetTaskInformationAsync
            Return MyBase.Channel.GetTaskInformationAsync(request)
        End Function
        
        Public Function GetTaskInformationAsync(ByVal strUserName As String, ByVal nIncidentNumber As Integer, ByVal strStepName As String) As System.Threading.Tasks.Task(Of Tramite_Asesorias.GetTaskInformationResponse)
            Dim inValue As Tramite_Asesorias.GetTaskInformationRequest = New Tramite_Asesorias.GetTaskInformationRequest()
            inValue.Body = New Tramite_Asesorias.GetTaskInformationRequestBody()
            inValue.Body.strUserName = strUserName
            inValue.Body.nIncidentNumber = nIncidentNumber
            inValue.Body.strStepName = strStepName
            Return CType(Me,Tramite_Asesorias.AtencionTramiteAseSoap).GetTaskInformationAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Tramite_Asesorias_AtencionTramiteAseSoap_CompleteStep(ByVal request As Tramite_Asesorias.CompleteStepRequest) As Tramite_Asesorias.CompleteStepResponse Implements Tramite_Asesorias.AtencionTramiteAseSoap.CompleteStep
            Return MyBase.Channel.CompleteStep(request)
        End Function
        
        Public Function CompleteStep(ByVal strUserName As String, ByRef nIncidentNumber As Integer, ByVal strStepName As String, ByVal strSummary As String, ByVal strMemo As String, ByVal bDisableAbort As Boolean, ByVal nPriority As Integer, ByVal strXML As String, ByVal bValidateXML As Boolean, <System.Runtime.InteropServices.OutAttribute()> ByRef strError As String) As Boolean
            Dim inValue As Tramite_Asesorias.CompleteStepRequest = New Tramite_Asesorias.CompleteStepRequest()
            inValue.Body = New Tramite_Asesorias.CompleteStepRequestBody()
            inValue.Body.strUserName = strUserName
            inValue.Body.nIncidentNumber = nIncidentNumber
            inValue.Body.strStepName = strStepName
            inValue.Body.strSummary = strSummary
            inValue.Body.strMemo = strMemo
            inValue.Body.bDisableAbort = bDisableAbort
            inValue.Body.nPriority = nPriority
            inValue.Body.strXML = strXML
            inValue.Body.bValidateXML = bValidateXML
            Dim retVal As Tramite_Asesorias.CompleteStepResponse = CType(Me,Tramite_Asesorias.AtencionTramiteAseSoap).CompleteStep(inValue)
            nIncidentNumber = retVal.Body.nIncidentNumber
            strError = retVal.Body.strError
            Return retVal.Body.CompleteStepResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Tramite_Asesorias_AtencionTramiteAseSoap_CompleteStepAsync(ByVal request As Tramite_Asesorias.CompleteStepRequest) As System.Threading.Tasks.Task(Of Tramite_Asesorias.CompleteStepResponse) Implements Tramite_Asesorias.AtencionTramiteAseSoap.CompleteStepAsync
            Return MyBase.Channel.CompleteStepAsync(request)
        End Function
        
        Public Function CompleteStepAsync(ByVal strUserName As String, ByVal nIncidentNumber As Integer, ByVal strStepName As String, ByVal strSummary As String, ByVal strMemo As String, ByVal bDisableAbort As Boolean, ByVal nPriority As Integer, ByVal strXML As String, ByVal bValidateXML As Boolean) As System.Threading.Tasks.Task(Of Tramite_Asesorias.CompleteStepResponse)
            Dim inValue As Tramite_Asesorias.CompleteStepRequest = New Tramite_Asesorias.CompleteStepRequest()
            inValue.Body = New Tramite_Asesorias.CompleteStepRequestBody()
            inValue.Body.strUserName = strUserName
            inValue.Body.nIncidentNumber = nIncidentNumber
            inValue.Body.strStepName = strStepName
            inValue.Body.strSummary = strSummary
            inValue.Body.strMemo = strMemo
            inValue.Body.bDisableAbort = bDisableAbort
            inValue.Body.nPriority = nPriority
            inValue.Body.strXML = strXML
            inValue.Body.bValidateXML = bValidateXML
            Return CType(Me,Tramite_Asesorias.AtencionTramiteAseSoap).CompleteStepAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Tramite_Asesorias_AtencionTramiteAseSoap_ReturnStep(ByVal request As Tramite_Asesorias.ReturnStepRequest) As Tramite_Asesorias.ReturnStepResponse Implements Tramite_Asesorias.AtencionTramiteAseSoap.ReturnStep
            Return MyBase.Channel.ReturnStep(request)
        End Function
        
        Public Function ReturnStep(ByVal strUserName As String, ByRef nIncidentNumber As Integer, ByVal strStepName As String, ByVal strSummary As String, ByVal strMemo As String, ByVal bDisableAbort As Boolean, ByVal nPriority As Integer, ByVal strXML As String, ByVal bValidateXML As Boolean, <System.Runtime.InteropServices.OutAttribute()> ByRef strError As String) As Boolean
            Dim inValue As Tramite_Asesorias.ReturnStepRequest = New Tramite_Asesorias.ReturnStepRequest()
            inValue.Body = New Tramite_Asesorias.ReturnStepRequestBody()
            inValue.Body.strUserName = strUserName
            inValue.Body.nIncidentNumber = nIncidentNumber
            inValue.Body.strStepName = strStepName
            inValue.Body.strSummary = strSummary
            inValue.Body.strMemo = strMemo
            inValue.Body.bDisableAbort = bDisableAbort
            inValue.Body.nPriority = nPriority
            inValue.Body.strXML = strXML
            inValue.Body.bValidateXML = bValidateXML
            Dim retVal As Tramite_Asesorias.ReturnStepResponse = CType(Me,Tramite_Asesorias.AtencionTramiteAseSoap).ReturnStep(inValue)
            nIncidentNumber = retVal.Body.nIncidentNumber
            strError = retVal.Body.strError
            Return retVal.Body.ReturnStepResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Tramite_Asesorias_AtencionTramiteAseSoap_ReturnStepAsync(ByVal request As Tramite_Asesorias.ReturnStepRequest) As System.Threading.Tasks.Task(Of Tramite_Asesorias.ReturnStepResponse) Implements Tramite_Asesorias.AtencionTramiteAseSoap.ReturnStepAsync
            Return MyBase.Channel.ReturnStepAsync(request)
        End Function
        
        Public Function ReturnStepAsync(ByVal strUserName As String, ByVal nIncidentNumber As Integer, ByVal strStepName As String, ByVal strSummary As String, ByVal strMemo As String, ByVal bDisableAbort As Boolean, ByVal nPriority As Integer, ByVal strXML As String, ByVal bValidateXML As Boolean) As System.Threading.Tasks.Task(Of Tramite_Asesorias.ReturnStepResponse)
            Dim inValue As Tramite_Asesorias.ReturnStepRequest = New Tramite_Asesorias.ReturnStepRequest()
            inValue.Body = New Tramite_Asesorias.ReturnStepRequestBody()
            inValue.Body.strUserName = strUserName
            inValue.Body.nIncidentNumber = nIncidentNumber
            inValue.Body.strStepName = strStepName
            inValue.Body.strSummary = strSummary
            inValue.Body.strMemo = strMemo
            inValue.Body.bDisableAbort = bDisableAbort
            inValue.Body.nPriority = nPriority
            inValue.Body.strXML = strXML
            inValue.Body.bValidateXML = bValidateXML
            Return CType(Me,Tramite_Asesorias.AtencionTramiteAseSoap).ReturnStepAsync(inValue)
        End Function
    End Class
End Namespace
