'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace WcfCorrespondenciaRecibida
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ComunicacionEntrada", [Namespace]:="http://schemas.datacontract.org/2004/07/BANCOLDEX.IntegracionOnbase.Model.Classes"& _ 
        ""),  _
     System.SerializableAttribute()>  _
    Partial Public Class ComunicacionEntrada
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AnexosField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AsuntoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DocumentHandleField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaRadicacionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FunsionarioAsignadoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NombreRazonSocialField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NumeroIdentificacionField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NumeroRadicadoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NumeroReferenciaRelacionadaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoIdentificacionField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Anexos() As String
            Get
                Return Me.AnexosField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AnexosField, value) <> true) Then
                    Me.AnexosField = value
                    Me.RaisePropertyChanged("Anexos")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Asunto() As String
            Get
                Return Me.AsuntoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AsuntoField, value) <> true) Then
                    Me.AsuntoField = value
                    Me.RaisePropertyChanged("Asunto")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DocumentHandle() As Long
            Get
                Return Me.DocumentHandleField
            End Get
            Set
                If (Me.DocumentHandleField.Equals(value) <> true) Then
                    Me.DocumentHandleField = value
                    Me.RaisePropertyChanged("DocumentHandle")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FechaRadicacion() As String
            Get
                Return Me.FechaRadicacionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FechaRadicacionField, value) <> true) Then
                    Me.FechaRadicacionField = value
                    Me.RaisePropertyChanged("FechaRadicacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FunsionarioAsignado() As String
            Get
                Return Me.FunsionarioAsignadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FunsionarioAsignadoField, value) <> true) Then
                    Me.FunsionarioAsignadoField = value
                    Me.RaisePropertyChanged("FunsionarioAsignado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NombreRazonSocial() As String
            Get
                Return Me.NombreRazonSocialField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NombreRazonSocialField, value) <> true) Then
                    Me.NombreRazonSocialField = value
                    Me.RaisePropertyChanged("NombreRazonSocial")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NumeroIdentificacion() As Long
            Get
                Return Me.NumeroIdentificacionField
            End Get
            Set
                If (Me.NumeroIdentificacionField.Equals(value) <> true) Then
                    Me.NumeroIdentificacionField = value
                    Me.RaisePropertyChanged("NumeroIdentificacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NumeroRadicado() As String
            Get
                Return Me.NumeroRadicadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NumeroRadicadoField, value) <> true) Then
                    Me.NumeroRadicadoField = value
                    Me.RaisePropertyChanged("NumeroRadicado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NumeroReferenciaRelacionada() As String
            Get
                Return Me.NumeroReferenciaRelacionadaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NumeroReferenciaRelacionadaField, value) <> true) Then
                    Me.NumeroReferenciaRelacionadaField = value
                    Me.RaisePropertyChanged("NumeroReferenciaRelacionada")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TipoIdentificacion() As String
            Get
                Return Me.TipoIdentificacionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipoIdentificacionField, value) <> true) Then
                    Me.TipoIdentificacionField = value
                    Me.RaisePropertyChanged("TipoIdentificacion")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ComunicacionRecibida", [Namespace]:="http://schemas.datacontract.org/2004/07/BANCOLDEX.IntegracionOnbase.Model.BANCOLD"& _ 
        "EXIntegracionOnbaseModel"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ComunicacionRecibida
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AsociacionComunicacionIncidenteField As System.Collections.Generic.List(Of WcfCorrespondenciaRecibida.AsociacionComunicacionIncidente)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AsuntoField As System.Nullable(Of Integer)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CantidadAnexosField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DocumentHandleField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaRadicacionField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FunsionarioAsignadoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HistoricoComunicacionRecibidaField As System.Collections.Generic.List(Of WcfCorrespondenciaRecibida.HistoricoComunicacionRecibida)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdAnexosField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NombreAnexosField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NombreRazonSocialField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NumeroIdentificacionField As System.Nullable(Of Long)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NumeroRadicadoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NumeroReferenciaRelacionadaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoIdentificacionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UsuarioField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AsociacionComunicacionIncidente() As System.Collections.Generic.List(Of WcfCorrespondenciaRecibida.AsociacionComunicacionIncidente)
            Get
                Return Me.AsociacionComunicacionIncidenteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AsociacionComunicacionIncidenteField, value) <> true) Then
                    Me.AsociacionComunicacionIncidenteField = value
                    Me.RaisePropertyChanged("AsociacionComunicacionIncidente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Asunto() As System.Nullable(Of Integer)
            Get
                Return Me.AsuntoField
            End Get
            Set
                If (Me.AsuntoField.Equals(value) <> true) Then
                    Me.AsuntoField = value
                    Me.RaisePropertyChanged("Asunto")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CantidadAnexos() As Integer
            Get
                Return Me.CantidadAnexosField
            End Get
            Set
                If (Me.CantidadAnexosField.Equals(value) <> true) Then
                    Me.CantidadAnexosField = value
                    Me.RaisePropertyChanged("CantidadAnexos")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DocumentHandle() As Long
            Get
                Return Me.DocumentHandleField
            End Get
            Set
                If (Me.DocumentHandleField.Equals(value) <> true) Then
                    Me.DocumentHandleField = value
                    Me.RaisePropertyChanged("DocumentHandle")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Fecha() As Date
            Get
                Return Me.FechaField
            End Get
            Set
                If (Me.FechaField.Equals(value) <> true) Then
                    Me.FechaField = value
                    Me.RaisePropertyChanged("Fecha")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FechaRadicacion() As System.Nullable(Of Date)
            Get
                Return Me.FechaRadicacionField
            End Get
            Set
                If (Me.FechaRadicacionField.Equals(value) <> true) Then
                    Me.FechaRadicacionField = value
                    Me.RaisePropertyChanged("FechaRadicacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FunsionarioAsignado() As String
            Get
                Return Me.FunsionarioAsignadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FunsionarioAsignadoField, value) <> true) Then
                    Me.FunsionarioAsignadoField = value
                    Me.RaisePropertyChanged("FunsionarioAsignado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property HistoricoComunicacionRecibida() As System.Collections.Generic.List(Of WcfCorrespondenciaRecibida.HistoricoComunicacionRecibida)
            Get
                Return Me.HistoricoComunicacionRecibidaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.HistoricoComunicacionRecibidaField, value) <> true) Then
                    Me.HistoricoComunicacionRecibidaField = value
                    Me.RaisePropertyChanged("HistoricoComunicacionRecibida")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Id() As Long
            Get
                Return Me.IdField
            End Get
            Set
                If (Me.IdField.Equals(value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdAnexos() As String
            Get
                Return Me.IdAnexosField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdAnexosField, value) <> true) Then
                    Me.IdAnexosField = value
                    Me.RaisePropertyChanged("IdAnexos")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NombreAnexos() As String
            Get
                Return Me.NombreAnexosField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NombreAnexosField, value) <> true) Then
                    Me.NombreAnexosField = value
                    Me.RaisePropertyChanged("NombreAnexos")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NombreRazonSocial() As String
            Get
                Return Me.NombreRazonSocialField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NombreRazonSocialField, value) <> true) Then
                    Me.NombreRazonSocialField = value
                    Me.RaisePropertyChanged("NombreRazonSocial")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NumeroIdentificacion() As System.Nullable(Of Long)
            Get
                Return Me.NumeroIdentificacionField
            End Get
            Set
                If (Me.NumeroIdentificacionField.Equals(value) <> true) Then
                    Me.NumeroIdentificacionField = value
                    Me.RaisePropertyChanged("NumeroIdentificacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NumeroRadicado() As String
            Get
                Return Me.NumeroRadicadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NumeroRadicadoField, value) <> true) Then
                    Me.NumeroRadicadoField = value
                    Me.RaisePropertyChanged("NumeroRadicado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NumeroReferenciaRelacionada() As String
            Get
                Return Me.NumeroReferenciaRelacionadaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NumeroReferenciaRelacionadaField, value) <> true) Then
                    Me.NumeroReferenciaRelacionadaField = value
                    Me.RaisePropertyChanged("NumeroReferenciaRelacionada")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TipoIdentificacion() As String
            Get
                Return Me.TipoIdentificacionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipoIdentificacionField, value) <> true) Then
                    Me.TipoIdentificacionField = value
                    Me.RaisePropertyChanged("TipoIdentificacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Usuario() As String
            Get
                Return Me.UsuarioField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UsuarioField, value) <> true) Then
                    Me.UsuarioField = value
                    Me.RaisePropertyChanged("Usuario")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="AsociacionComunicacionIncidente", [Namespace]:="http://schemas.datacontract.org/2004/07/BANCOLDEX.IntegracionOnbase.Model.BANCOLD"& _ 
        "EXIntegracionOnbaseModel"),  _
     System.SerializableAttribute()>  _
    Partial Public Class AsociacionComunicacionIncidente
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ComunicacionRecibidaField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ComunicacionRecibida1Field As WcfCorrespondenciaRecibida.ComunicacionRecibida
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CreadoField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IncidenteField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProcesoField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ComunicacionRecibida() As Long
            Get
                Return Me.ComunicacionRecibidaField
            End Get
            Set
                If (Me.ComunicacionRecibidaField.Equals(value) <> true) Then
                    Me.ComunicacionRecibidaField = value
                    Me.RaisePropertyChanged("ComunicacionRecibida")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ComunicacionRecibida1() As WcfCorrespondenciaRecibida.ComunicacionRecibida
            Get
                Return Me.ComunicacionRecibida1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.ComunicacionRecibida1Field, value) <> true) Then
                    Me.ComunicacionRecibida1Field = value
                    Me.RaisePropertyChanged("ComunicacionRecibida1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Creado() As Boolean
            Get
                Return Me.CreadoField
            End Get
            Set
                If (Me.CreadoField.Equals(value) <> true) Then
                    Me.CreadoField = value
                    Me.RaisePropertyChanged("Creado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Id() As Long
            Get
                Return Me.IdField
            End Get
            Set
                If (Me.IdField.Equals(value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Incidente() As Integer
            Get
                Return Me.IncidenteField
            End Get
            Set
                If (Me.IncidenteField.Equals(value) <> true) Then
                    Me.IncidenteField = value
                    Me.RaisePropertyChanged("Incidente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Proceso() As String
            Get
                Return Me.ProcesoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProcesoField, value) <> true) Then
                    Me.ProcesoField = value
                    Me.RaisePropertyChanged("Proceso")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="HistoricoComunicacionRecibida", [Namespace]:="http://schemas.datacontract.org/2004/07/BANCOLDEX.IntegracionOnbase.Model.BANCOLD"& _ 
        "EXIntegracionOnbaseModel"),  _
     System.SerializableAttribute()>  _
    Partial Public Class HistoricoComunicacionRecibida
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AsuntoField As System.Nullable(Of Integer)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ComunicacionRecibidaField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ComunicacionRecibida1Field As WcfCorrespondenciaRecibida.ComunicacionRecibida
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NombreRazonSocialField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NumeroIdentificacionField As System.Nullable(Of Long)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NumeroReferenciaRelacionadaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoIdentificacionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UsuarioField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Asunto() As System.Nullable(Of Integer)
            Get
                Return Me.AsuntoField
            End Get
            Set
                If (Me.AsuntoField.Equals(value) <> true) Then
                    Me.AsuntoField = value
                    Me.RaisePropertyChanged("Asunto")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ComunicacionRecibida() As Long
            Get
                Return Me.ComunicacionRecibidaField
            End Get
            Set
                If (Me.ComunicacionRecibidaField.Equals(value) <> true) Then
                    Me.ComunicacionRecibidaField = value
                    Me.RaisePropertyChanged("ComunicacionRecibida")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ComunicacionRecibida1() As WcfCorrespondenciaRecibida.ComunicacionRecibida
            Get
                Return Me.ComunicacionRecibida1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.ComunicacionRecibida1Field, value) <> true) Then
                    Me.ComunicacionRecibida1Field = value
                    Me.RaisePropertyChanged("ComunicacionRecibida1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Fecha() As Date
            Get
                Return Me.FechaField
            End Get
            Set
                If (Me.FechaField.Equals(value) <> true) Then
                    Me.FechaField = value
                    Me.RaisePropertyChanged("Fecha")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Id() As Long
            Get
                Return Me.IdField
            End Get
            Set
                If (Me.IdField.Equals(value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NombreRazonSocial() As String
            Get
                Return Me.NombreRazonSocialField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NombreRazonSocialField, value) <> true) Then
                    Me.NombreRazonSocialField = value
                    Me.RaisePropertyChanged("NombreRazonSocial")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NumeroIdentificacion() As System.Nullable(Of Long)
            Get
                Return Me.NumeroIdentificacionField
            End Get
            Set
                If (Me.NumeroIdentificacionField.Equals(value) <> true) Then
                    Me.NumeroIdentificacionField = value
                    Me.RaisePropertyChanged("NumeroIdentificacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NumeroReferenciaRelacionada() As String
            Get
                Return Me.NumeroReferenciaRelacionadaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NumeroReferenciaRelacionadaField, value) <> true) Then
                    Me.NumeroReferenciaRelacionadaField = value
                    Me.RaisePropertyChanged("NumeroReferenciaRelacionada")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TipoIdentificacion() As String
            Get
                Return Me.TipoIdentificacionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipoIdentificacionField, value) <> true) Then
                    Me.TipoIdentificacionField = value
                    Me.RaisePropertyChanged("TipoIdentificacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Usuario() As String
            Get
                Return Me.UsuarioField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UsuarioField, value) <> true) Then
                    Me.UsuarioField = value
                    Me.RaisePropertyChanged("Usuario")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WcfCorrespondenciaRecibida.IServicioIntegracion")>  _
    Public Interface IServicioIntegracion
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicioIntegracion/IntegracionOnbase", ReplyAction:="http://tempuri.org/IServicioIntegracion/IntegracionOnbaseResponse")>  _
        Function IntegracionOnbase(ByVal comunicacionEntrada As WcfCorrespondenciaRecibida.ComunicacionEntrada) As Long
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicioIntegracion/ModificarComunicacionRecibida", ReplyAction:="http://tempuri.org/IServicioIntegracion/ModificarComunicacionRecibidaResponse")>  _
        Function ModificarComunicacionRecibida(ByVal comunicacionRecibida As WcfCorrespondenciaRecibida.ComunicacionRecibida) As Long
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicioIntegracion/DevolverCorrespondencia", ReplyAction:="http://tempuri.org/IServicioIntegracion/DevolverCorrespondenciaResponse")>  _
        Function DevolverCorrespondencia(ByVal idComunicacion As Long, ByVal usuario As String, ByVal comentarios As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicioIntegracion/AsociarCorrespondencia", ReplyAction:="http://tempuri.org/IServicioIntegracion/AsociarCorrespondenciaResponse")>  _
        Function AsociarCorrespondencia(ByVal idComunicacion As Long, ByVal proceso As String, ByVal incidente As Integer) As Boolean
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IServicioIntegracionChannel
        Inherits WcfCorrespondenciaRecibida.IServicioIntegracion, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServicioIntegracionClient
        Inherits System.ServiceModel.ClientBase(Of WcfCorrespondenciaRecibida.IServicioIntegracion)
        Implements WcfCorrespondenciaRecibida.IServicioIntegracion
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function IntegracionOnbase(ByVal comunicacionEntrada As WcfCorrespondenciaRecibida.ComunicacionEntrada) As Long Implements WcfCorrespondenciaRecibida.IServicioIntegracion.IntegracionOnbase
            Return MyBase.Channel.IntegracionOnbase(comunicacionEntrada)
        End Function
        
        Public Function ModificarComunicacionRecibida(ByVal comunicacionRecibida As WcfCorrespondenciaRecibida.ComunicacionRecibida) As Long Implements WcfCorrespondenciaRecibida.IServicioIntegracion.ModificarComunicacionRecibida
            Return MyBase.Channel.ModificarComunicacionRecibida(comunicacionRecibida)
        End Function
        
        Public Function DevolverCorrespondencia(ByVal idComunicacion As Long, ByVal usuario As String, ByVal comentarios As String) As Boolean Implements WcfCorrespondenciaRecibida.IServicioIntegracion.DevolverCorrespondencia
            Return MyBase.Channel.DevolverCorrespondencia(idComunicacion, usuario, comentarios)
        End Function
        
        Public Function AsociarCorrespondencia(ByVal idComunicacion As Long, ByVal proceso As String, ByVal incidente As Integer) As Boolean Implements WcfCorrespondenciaRecibida.IServicioIntegracion.AsociarCorrespondencia
            Return MyBase.Channel.AsociarCorrespondencia(idComunicacion, proceso, incidente)
        End Function
    End Class
End Namespace
