'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace UltimusBIS
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.ultimus.com/BIS", ConfigurationName:="UltimusBIS.UltimusBISSoap")>  _
    Public Interface UltimusBISSoap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetBPMSchemaResult del espacio de nombres http://www.ultimus.com/BIS no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ultimus.com/BIS/GetBPMSchema", ReplyAction:="*")>  _
        Function GetBPMSchema(ByVal request As UltimusBIS.GetBPMSchemaRequest) As UltimusBIS.GetBPMSchemaResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento xquery del espacio de nombres http://www.ultimus.com/BIS no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ultimus.com/BIS/GetBPMQuerySchema", ReplyAction:="*")>  _
        Function GetBPMQuerySchema(ByVal request As UltimusBIS.GetBPMQuerySchemaRequest) As UltimusBIS.GetBPMQuerySchemaResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento process del espacio de nombres http://www.ultimus.com/BIS no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ultimus.com/BIS/GetProcessQuerySchema", ReplyAction:="*")>  _
        Function GetProcessQuerySchema(ByVal request As UltimusBIS.GetProcessQuerySchemaRequest) As UltimusBIS.GetProcessQuerySchemaResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento process del espacio de nombres http://www.ultimus.com/BIS no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ultimus.com/BIS/GetProcessStepQuerySchema", ReplyAction:="*")>  _
        Function GetProcessStepQuerySchema(ByVal request As UltimusBIS.GetProcessStepQuerySchemaRequest) As UltimusBIS.GetProcessStepQuerySchemaResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento process del espacio de nombres http://www.ultimus.com/BIS no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ultimus.com/BIS/GetProcessSchema", ReplyAction:="*")>  _
        Function GetProcessSchema(ByVal request As UltimusBIS.GetProcessSchemaRequest) As UltimusBIS.GetProcessSchemaResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento process del espacio de nombres http://www.ultimus.com/BIS no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ultimus.com/BIS/GetProcessStepSchema", ReplyAction:="*")>  _
        Function GetProcessStepSchema(ByVal request As UltimusBIS.GetProcessStepSchemaRequest) As UltimusBIS.GetProcessStepSchemaResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento xquery del espacio de nombres http://www.ultimus.com/BIS no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ultimus.com/BIS/RunBPMQuery", ReplyAction:="*")>  _
        Function RunBPMQuery(ByVal request As UltimusBIS.RunBPMQueryRequest) As UltimusBIS.RunBPMQueryResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento process del espacio de nombres http://www.ultimus.com/BIS no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ultimus.com/BIS/RunProcessQuery", ReplyAction:="*")>  _
        Function RunProcessQuery(ByVal request As UltimusBIS.RunProcessQueryRequest) As UltimusBIS.RunProcessQueryResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento process del espacio de nombres http://www.ultimus.com/BIS no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ultimus.com/BIS/RunProcessStepQuery", ReplyAction:="*")>  _
        Function RunProcessStepQuery(ByVal request As UltimusBIS.RunProcessStepQueryRequest) As UltimusBIS.RunProcessStepQueryResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetBPMSchemaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetBPMSchema", [Namespace]:="http://www.ultimus.com/BIS", Order:=0)>  _
        Public Body As UltimusBIS.GetBPMSchemaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UltimusBIS.GetBPMSchemaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class GetBPMSchemaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetBPMSchemaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetBPMSchemaResponse", [Namespace]:="http://www.ultimus.com/BIS", Order:=0)>  _
        Public Body As UltimusBIS.GetBPMSchemaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UltimusBIS.GetBPMSchemaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/BIS")>  _
    Partial Public Class GetBPMSchemaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetBPMSchemaResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetBPMSchemaResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.GetBPMSchemaResult = GetBPMSchemaResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetBPMQuerySchemaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetBPMQuerySchema", [Namespace]:="http://www.ultimus.com/BIS", Order:=0)>  _
        Public Body As UltimusBIS.GetBPMQuerySchemaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UltimusBIS.GetBPMQuerySchemaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/BIS")>  _
    Partial Public Class GetBPMQuerySchemaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public xquery As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal xquery As String)
            MyBase.New
            Me.xquery = xquery
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetBPMQuerySchemaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetBPMQuerySchemaResponse", [Namespace]:="http://www.ultimus.com/BIS", Order:=0)>  _
        Public Body As UltimusBIS.GetBPMQuerySchemaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UltimusBIS.GetBPMQuerySchemaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/BIS")>  _
    Partial Public Class GetBPMQuerySchemaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetBPMQuerySchemaResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetBPMQuerySchemaResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.GetBPMQuerySchemaResult = GetBPMQuerySchemaResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetProcessQuerySchemaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetProcessQuerySchema", [Namespace]:="http://www.ultimus.com/BIS", Order:=0)>  _
        Public Body As UltimusBIS.GetProcessQuerySchemaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UltimusBIS.GetProcessQuerySchemaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/BIS")>  _
    Partial Public Class GetProcessQuerySchemaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public process As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public version As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public xquery As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal process As String, ByVal version As Integer, ByVal xquery As String)
            MyBase.New
            Me.process = process
            Me.version = version
            Me.xquery = xquery
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetProcessQuerySchemaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetProcessQuerySchemaResponse", [Namespace]:="http://www.ultimus.com/BIS", Order:=0)>  _
        Public Body As UltimusBIS.GetProcessQuerySchemaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UltimusBIS.GetProcessQuerySchemaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/BIS")>  _
    Partial Public Class GetProcessQuerySchemaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetProcessQuerySchemaResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetProcessQuerySchemaResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.GetProcessQuerySchemaResult = GetProcessQuerySchemaResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetProcessStepQuerySchemaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetProcessStepQuerySchema", [Namespace]:="http://www.ultimus.com/BIS", Order:=0)>  _
        Public Body As UltimusBIS.GetProcessStepQuerySchemaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UltimusBIS.GetProcessStepQuerySchemaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/BIS")>  _
    Partial Public Class GetProcessStepQuerySchemaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public process As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public version As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public [step] As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public xquery As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal process As String, ByVal version As Integer, ByVal [step] As String, ByVal xquery As String)
            MyBase.New
            Me.process = process
            Me.version = version
            Me.[step] = [step]
            Me.xquery = xquery
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetProcessStepQuerySchemaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetProcessStepQuerySchemaResponse", [Namespace]:="http://www.ultimus.com/BIS", Order:=0)>  _
        Public Body As UltimusBIS.GetProcessStepQuerySchemaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UltimusBIS.GetProcessStepQuerySchemaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/BIS")>  _
    Partial Public Class GetProcessStepQuerySchemaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetProcessStepQuerySchemaResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetProcessStepQuerySchemaResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.GetProcessStepQuerySchemaResult = GetProcessStepQuerySchemaResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetProcessSchemaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetProcessSchema", [Namespace]:="http://www.ultimus.com/BIS", Order:=0)>  _
        Public Body As UltimusBIS.GetProcessSchemaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UltimusBIS.GetProcessSchemaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/BIS")>  _
    Partial Public Class GetProcessSchemaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public process As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public version As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal process As String, ByVal version As Integer)
            MyBase.New
            Me.process = process
            Me.version = version
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetProcessSchemaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetProcessSchemaResponse", [Namespace]:="http://www.ultimus.com/BIS", Order:=0)>  _
        Public Body As UltimusBIS.GetProcessSchemaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UltimusBIS.GetProcessSchemaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/BIS")>  _
    Partial Public Class GetProcessSchemaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetProcessSchemaResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetProcessSchemaResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.GetProcessSchemaResult = GetProcessSchemaResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetProcessStepSchemaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetProcessStepSchema", [Namespace]:="http://www.ultimus.com/BIS", Order:=0)>  _
        Public Body As UltimusBIS.GetProcessStepSchemaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UltimusBIS.GetProcessStepSchemaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/BIS")>  _
    Partial Public Class GetProcessStepSchemaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public process As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public version As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public [step] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal process As String, ByVal version As Integer, ByVal [step] As String)
            MyBase.New
            Me.process = process
            Me.version = version
            Me.[step] = [step]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetProcessStepSchemaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetProcessStepSchemaResponse", [Namespace]:="http://www.ultimus.com/BIS", Order:=0)>  _
        Public Body As UltimusBIS.GetProcessStepSchemaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UltimusBIS.GetProcessStepSchemaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/BIS")>  _
    Partial Public Class GetProcessStepSchemaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetProcessStepSchemaResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetProcessStepSchemaResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.GetProcessStepSchemaResult = GetProcessStepSchemaResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RunBPMQueryRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="RunBPMQuery", [Namespace]:="http://www.ultimus.com/BIS", Order:=0)>  _
        Public Body As UltimusBIS.RunBPMQueryRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UltimusBIS.RunBPMQueryRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/BIS")>  _
    Partial Public Class RunBPMQueryRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public xquery As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public use_archived_data As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal xquery As String, ByVal use_archived_data As Boolean)
            MyBase.New
            Me.xquery = xquery
            Me.use_archived_data = use_archived_data
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RunBPMQueryResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="RunBPMQueryResponse", [Namespace]:="http://www.ultimus.com/BIS", Order:=0)>  _
        Public Body As UltimusBIS.RunBPMQueryResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UltimusBIS.RunBPMQueryResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/BIS")>  _
    Partial Public Class RunBPMQueryResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public RunBPMQueryResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RunBPMQueryResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.RunBPMQueryResult = RunBPMQueryResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RunProcessQueryRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="RunProcessQuery", [Namespace]:="http://www.ultimus.com/BIS", Order:=0)>  _
        Public Body As UltimusBIS.RunProcessQueryRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UltimusBIS.RunProcessQueryRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/BIS")>  _
    Partial Public Class RunProcessQueryRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public process As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public version As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public xquery As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public use_archived_data As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal process As String, ByVal version As Integer, ByVal xquery As String, ByVal use_archived_data As Boolean)
            MyBase.New
            Me.process = process
            Me.version = version
            Me.xquery = xquery
            Me.use_archived_data = use_archived_data
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RunProcessQueryResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="RunProcessQueryResponse", [Namespace]:="http://www.ultimus.com/BIS", Order:=0)>  _
        Public Body As UltimusBIS.RunProcessQueryResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UltimusBIS.RunProcessQueryResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/BIS")>  _
    Partial Public Class RunProcessQueryResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public RunProcessQueryResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RunProcessQueryResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.RunProcessQueryResult = RunProcessQueryResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RunProcessStepQueryRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="RunProcessStepQuery", [Namespace]:="http://www.ultimus.com/BIS", Order:=0)>  _
        Public Body As UltimusBIS.RunProcessStepQueryRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UltimusBIS.RunProcessStepQueryRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/BIS")>  _
    Partial Public Class RunProcessStepQueryRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public process As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public version As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public [step] As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public xquery As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public use_archived_data As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal process As String, ByVal version As Integer, ByVal [step] As String, ByVal xquery As String, ByVal use_archived_data As Boolean)
            MyBase.New
            Me.process = process
            Me.version = version
            Me.[step] = [step]
            Me.xquery = xquery
            Me.use_archived_data = use_archived_data
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RunProcessStepQueryResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="RunProcessStepQueryResponse", [Namespace]:="http://www.ultimus.com/BIS", Order:=0)>  _
        Public Body As UltimusBIS.RunProcessStepQueryResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UltimusBIS.RunProcessStepQueryResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.ultimus.com/BIS")>  _
    Partial Public Class RunProcessStepQueryResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public RunProcessStepQueryResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RunProcessStepQueryResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.RunProcessStepQueryResult = RunProcessStepQueryResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface UltimusBISSoapChannel
        Inherits UltimusBIS.UltimusBISSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class UltimusBISSoapClient
        Inherits System.ServiceModel.ClientBase(Of UltimusBIS.UltimusBISSoap)
        Implements UltimusBIS.UltimusBISSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UltimusBIS_UltimusBISSoap_GetBPMSchema(ByVal request As UltimusBIS.GetBPMSchemaRequest) As UltimusBIS.GetBPMSchemaResponse Implements UltimusBIS.UltimusBISSoap.GetBPMSchema
            Return MyBase.Channel.GetBPMSchema(request)
        End Function
        
        Public Function GetBPMSchema() As System.Xml.Linq.XElement
            Dim inValue As UltimusBIS.GetBPMSchemaRequest = New UltimusBIS.GetBPMSchemaRequest()
            inValue.Body = New UltimusBIS.GetBPMSchemaRequestBody()
            Dim retVal As UltimusBIS.GetBPMSchemaResponse = CType(Me,UltimusBIS.UltimusBISSoap).GetBPMSchema(inValue)
            Return retVal.Body.GetBPMSchemaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UltimusBIS_UltimusBISSoap_GetBPMQuerySchema(ByVal request As UltimusBIS.GetBPMQuerySchemaRequest) As UltimusBIS.GetBPMQuerySchemaResponse Implements UltimusBIS.UltimusBISSoap.GetBPMQuerySchema
            Return MyBase.Channel.GetBPMQuerySchema(request)
        End Function
        
        Public Function GetBPMQuerySchema(ByVal xquery As String) As System.Xml.Linq.XElement
            Dim inValue As UltimusBIS.GetBPMQuerySchemaRequest = New UltimusBIS.GetBPMQuerySchemaRequest()
            inValue.Body = New UltimusBIS.GetBPMQuerySchemaRequestBody()
            inValue.Body.xquery = xquery
            Dim retVal As UltimusBIS.GetBPMQuerySchemaResponse = CType(Me,UltimusBIS.UltimusBISSoap).GetBPMQuerySchema(inValue)
            Return retVal.Body.GetBPMQuerySchemaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UltimusBIS_UltimusBISSoap_GetProcessQuerySchema(ByVal request As UltimusBIS.GetProcessQuerySchemaRequest) As UltimusBIS.GetProcessQuerySchemaResponse Implements UltimusBIS.UltimusBISSoap.GetProcessQuerySchema
            Return MyBase.Channel.GetProcessQuerySchema(request)
        End Function
        
        Public Function GetProcessQuerySchema(ByVal process As String, ByVal version As Integer, ByVal xquery As String) As System.Xml.Linq.XElement
            Dim inValue As UltimusBIS.GetProcessQuerySchemaRequest = New UltimusBIS.GetProcessQuerySchemaRequest()
            inValue.Body = New UltimusBIS.GetProcessQuerySchemaRequestBody()
            inValue.Body.process = process
            inValue.Body.version = version
            inValue.Body.xquery = xquery
            Dim retVal As UltimusBIS.GetProcessQuerySchemaResponse = CType(Me,UltimusBIS.UltimusBISSoap).GetProcessQuerySchema(inValue)
            Return retVal.Body.GetProcessQuerySchemaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UltimusBIS_UltimusBISSoap_GetProcessStepQuerySchema(ByVal request As UltimusBIS.GetProcessStepQuerySchemaRequest) As UltimusBIS.GetProcessStepQuerySchemaResponse Implements UltimusBIS.UltimusBISSoap.GetProcessStepQuerySchema
            Return MyBase.Channel.GetProcessStepQuerySchema(request)
        End Function
        
        Public Function GetProcessStepQuerySchema(ByVal process As String, ByVal version As Integer, ByVal [step] As String, ByVal xquery As String) As System.Xml.Linq.XElement
            Dim inValue As UltimusBIS.GetProcessStepQuerySchemaRequest = New UltimusBIS.GetProcessStepQuerySchemaRequest()
            inValue.Body = New UltimusBIS.GetProcessStepQuerySchemaRequestBody()
            inValue.Body.process = process
            inValue.Body.version = version
            inValue.Body.[step] = [step]
            inValue.Body.xquery = xquery
            Dim retVal As UltimusBIS.GetProcessStepQuerySchemaResponse = CType(Me,UltimusBIS.UltimusBISSoap).GetProcessStepQuerySchema(inValue)
            Return retVal.Body.GetProcessStepQuerySchemaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UltimusBIS_UltimusBISSoap_GetProcessSchema(ByVal request As UltimusBIS.GetProcessSchemaRequest) As UltimusBIS.GetProcessSchemaResponse Implements UltimusBIS.UltimusBISSoap.GetProcessSchema
            Return MyBase.Channel.GetProcessSchema(request)
        End Function
        
        Public Function GetProcessSchema(ByVal process As String, ByVal version As Integer) As System.Xml.Linq.XElement
            Dim inValue As UltimusBIS.GetProcessSchemaRequest = New UltimusBIS.GetProcessSchemaRequest()
            inValue.Body = New UltimusBIS.GetProcessSchemaRequestBody()
            inValue.Body.process = process
            inValue.Body.version = version
            Dim retVal As UltimusBIS.GetProcessSchemaResponse = CType(Me,UltimusBIS.UltimusBISSoap).GetProcessSchema(inValue)
            Return retVal.Body.GetProcessSchemaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UltimusBIS_UltimusBISSoap_GetProcessStepSchema(ByVal request As UltimusBIS.GetProcessStepSchemaRequest) As UltimusBIS.GetProcessStepSchemaResponse Implements UltimusBIS.UltimusBISSoap.GetProcessStepSchema
            Return MyBase.Channel.GetProcessStepSchema(request)
        End Function
        
        Public Function GetProcessStepSchema(ByVal process As String, ByVal version As Integer, ByVal [step] As String) As System.Xml.Linq.XElement
            Dim inValue As UltimusBIS.GetProcessStepSchemaRequest = New UltimusBIS.GetProcessStepSchemaRequest()
            inValue.Body = New UltimusBIS.GetProcessStepSchemaRequestBody()
            inValue.Body.process = process
            inValue.Body.version = version
            inValue.Body.[step] = [step]
            Dim retVal As UltimusBIS.GetProcessStepSchemaResponse = CType(Me,UltimusBIS.UltimusBISSoap).GetProcessStepSchema(inValue)
            Return retVal.Body.GetProcessStepSchemaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UltimusBIS_UltimusBISSoap_RunBPMQuery(ByVal request As UltimusBIS.RunBPMQueryRequest) As UltimusBIS.RunBPMQueryResponse Implements UltimusBIS.UltimusBISSoap.RunBPMQuery
            Return MyBase.Channel.RunBPMQuery(request)
        End Function
        
        Public Function RunBPMQuery(ByVal xquery As String, ByVal use_archived_data As Boolean) As System.Xml.Linq.XElement
            Dim inValue As UltimusBIS.RunBPMQueryRequest = New UltimusBIS.RunBPMQueryRequest()
            inValue.Body = New UltimusBIS.RunBPMQueryRequestBody()
            inValue.Body.xquery = xquery
            inValue.Body.use_archived_data = use_archived_data
            Dim retVal As UltimusBIS.RunBPMQueryResponse = CType(Me,UltimusBIS.UltimusBISSoap).RunBPMQuery(inValue)
            Return retVal.Body.RunBPMQueryResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UltimusBIS_UltimusBISSoap_RunProcessQuery(ByVal request As UltimusBIS.RunProcessQueryRequest) As UltimusBIS.RunProcessQueryResponse Implements UltimusBIS.UltimusBISSoap.RunProcessQuery
            Return MyBase.Channel.RunProcessQuery(request)
        End Function
        
        Public Function RunProcessQuery(ByVal process As String, ByVal version As Integer, ByVal xquery As String, ByVal use_archived_data As Boolean) As System.Xml.Linq.XElement
            Dim inValue As UltimusBIS.RunProcessQueryRequest = New UltimusBIS.RunProcessQueryRequest()
            inValue.Body = New UltimusBIS.RunProcessQueryRequestBody()
            inValue.Body.process = process
            inValue.Body.version = version
            inValue.Body.xquery = xquery
            inValue.Body.use_archived_data = use_archived_data
            Dim retVal As UltimusBIS.RunProcessQueryResponse = CType(Me,UltimusBIS.UltimusBISSoap).RunProcessQuery(inValue)
            Return retVal.Body.RunProcessQueryResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UltimusBIS_UltimusBISSoap_RunProcessStepQuery(ByVal request As UltimusBIS.RunProcessStepQueryRequest) As UltimusBIS.RunProcessStepQueryResponse Implements UltimusBIS.UltimusBISSoap.RunProcessStepQuery
            Return MyBase.Channel.RunProcessStepQuery(request)
        End Function
        
        Public Function RunProcessStepQuery(ByVal process As String, ByVal version As Integer, ByVal [step] As String, ByVal xquery As String, ByVal use_archived_data As Boolean) As System.Xml.Linq.XElement
            Dim inValue As UltimusBIS.RunProcessStepQueryRequest = New UltimusBIS.RunProcessStepQueryRequest()
            inValue.Body = New UltimusBIS.RunProcessStepQueryRequestBody()
            inValue.Body.process = process
            inValue.Body.version = version
            inValue.Body.[step] = [step]
            inValue.Body.xquery = xquery
            inValue.Body.use_archived_data = use_archived_data
            Dim retVal As UltimusBIS.RunProcessStepQueryResponse = CType(Me,UltimusBIS.UltimusBISSoap).RunProcessStepQuery(inValue)
            Return retVal.Body.RunProcessStepQueryResult
        End Function
    End Class
End Namespace
